package modelo;
// Generated Nov 18, 2015 4:27:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int matricula;
     private Carrera carrera;
     private String nombre;
     private String paterno;
     private String materno;
     private String email;
     private String fnacimiento;
     private String tipo;
     private Set<Respuesta> respuestas = new HashSet<Respuesta>(0);
     private Set<Examen> examens = new HashSet<Examen>(0);

    public Alumno() {
    }

	
    public Alumno(int matricula, Carrera carrera, String nombre, String paterno, String materno, String email, String fnacimiento, String tipo) {
        this.matricula = matricula;
        this.carrera = carrera;
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
        this.email = email;
        this.fnacimiento = fnacimiento;
        this.tipo = tipo;
    }
    public Alumno(int matricula, Carrera carrera, String nombre, String paterno, String materno, String email, String fnacimiento, String tipo, Set<Respuesta> respuestas, Set<Examen> examens) {
       this.matricula = matricula;
       this.carrera = carrera;
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.email = email;
       this.fnacimiento = fnacimiento;
       this.tipo = tipo;
       this.respuestas = respuestas;
       this.examens = examens;
    }
   
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFnacimiento() {
        return this.fnacimiento;
    }
    
    public void setFnacimiento(String fnacimiento) {
        this.fnacimiento = fnacimiento;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Respuesta> getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set<Respuesta> respuestas) {
        this.respuestas = respuestas;
    }
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }




}


