package modelo;
// Generated Nov 18, 2015 4:27:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private int idcarrera;
     private Escuela escuela;
     private String nombre;
     private String duracion;
     private Set<Materia> materias = new HashSet<Materia>(0);
     private Set<Materia> materias_1 = new HashSet<Materia>(0);
     private Set<Alumno> alumnos = new HashSet<Alumno>(0);
     private Set<Alumno> alumnos_1 = new HashSet<Alumno>(0);

    public Carrera() {
    }

	
    public Carrera(int idcarrera, Escuela escuela, String nombre, String duracion) {
        this.idcarrera = idcarrera;
        this.escuela = escuela;
        this.nombre = nombre;
        this.duracion = duracion;
    }
    public Carrera(int idcarrera, Escuela escuela, String nombre, String duracion, Set<Materia> materias, Set<Materia> materias_1, Set<Alumno> alumnos, Set<Alumno> alumnos_1) {
       this.idcarrera = idcarrera;
       this.escuela = escuela;
       this.nombre = nombre;
       this.duracion = duracion;
       this.materias = materias;
       this.materias_1 = materias_1;
       this.alumnos = alumnos;
       this.alumnos_1 = alumnos_1;
    }
   
    public int getIdcarrera() {
        return this.idcarrera;
    }
    
    public void setIdcarrera(int idcarrera) {
        this.idcarrera = idcarrera;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public Set<Materia> getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Set<Materia> materias) {
        this.materias = materias;
    }
    public Set<Materia> getMaterias_1() {
        return this.materias_1;
    }
    
    public void setMaterias_1(Set<Materia> materias_1) {
        this.materias_1 = materias_1;
    }
    public Set<Alumno> getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set<Alumno> alumnos) {
        this.alumnos = alumnos;
    }
    public Set<Alumno> getAlumnos_1() {
        return this.alumnos_1;
    }
    
    public void setAlumnos_1(Set<Alumno> alumnos_1) {
        this.alumnos_1 = alumnos_1;
    }




}


