package modelo;
// Generated Nov 18, 2015 4:27:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private int idexamen;
     private Materia materia;
     private String parcial;
     private Set<Alumno> alumnos = new HashSet<Alumno>(0);
     private Set<Pregunta> preguntas = new HashSet<Pregunta>(0);
     private Set<Pregunta> preguntas_1 = new HashSet<Pregunta>(0);

    public Examen() {
    }

	
    public Examen(int idexamen, Materia materia, String parcial) {
        this.idexamen = idexamen;
        this.materia = materia;
        this.parcial = parcial;
    }
    public Examen(int idexamen, Materia materia, String parcial, Set<Alumno> alumnos, Set<Pregunta> preguntas, Set<Pregunta> preguntas_1) {
       this.idexamen = idexamen;
       this.materia = materia;
       this.parcial = parcial;
       this.alumnos = alumnos;
       this.preguntas = preguntas;
       this.preguntas_1 = preguntas_1;
    }
   
    public int getIdexamen() {
        return this.idexamen;
    }
    
    public void setIdexamen(int idexamen) {
        this.idexamen = idexamen;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public String getParcial() {
        return this.parcial;
    }
    
    public void setParcial(String parcial) {
        this.parcial = parcial;
    }
    public Set<Alumno> getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set<Alumno> alumnos) {
        this.alumnos = alumnos;
    }
    public Set<Pregunta> getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set<Pregunta> preguntas) {
        this.preguntas = preguntas;
    }
    public Set<Pregunta> getPreguntas_1() {
        return this.preguntas_1;
    }
    
    public void setPreguntas_1(Set<Pregunta> preguntas_1) {
        this.preguntas_1 = preguntas_1;
    }




}


