package modelo;
// Generated Nov 18, 2015 4:27:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private int idmateria;
     private Carrera carrera;
     private String nombre;
     private String credito;
     private Set<Examen> examens = new HashSet<Examen>(0);
     private Set<Examen> examens_1 = new HashSet<Examen>(0);

    public Materia() {
    }

	
    public Materia(int idmateria, Carrera carrera, String nombre, String credito) {
        this.idmateria = idmateria;
        this.carrera = carrera;
        this.nombre = nombre;
        this.credito = credito;
    }
    public Materia(int idmateria, Carrera carrera, String nombre, String credito, Set<Examen> examens, Set<Examen> examens_1) {
       this.idmateria = idmateria;
       this.carrera = carrera;
       this.nombre = nombre;
       this.credito = credito;
       this.examens = examens;
       this.examens_1 = examens_1;
    }
   
    public int getIdmateria() {
        return this.idmateria;
    }
    
    public void setIdmateria(int idmateria) {
        this.idmateria = idmateria;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCredito() {
        return this.credito;
    }
    
    public void setCredito(String credito) {
        this.credito = credito;
    }
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }
    public Set<Examen> getExamens_1() {
        return this.examens_1;
    }
    
    public void setExamens_1(Set<Examen> examens_1) {
        this.examens_1 = examens_1;
    }




}


