package modelo;
// Generated Nov 18, 2015 4:27:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int idpregunta;
     private Examen examen;
     private String pregunta;
     private String respuestacorrecta;
     private Set<Respuesta> respuestas = new HashSet<Respuesta>(0);
     private Set<Respuesta> respuestas_1 = new HashSet<Respuesta>(0);

    public Pregunta() {
    }

	
    public Pregunta(int idpregunta, Examen examen, String pregunta, String respuestacorrecta) {
        this.idpregunta = idpregunta;
        this.examen = examen;
        this.pregunta = pregunta;
        this.respuestacorrecta = respuestacorrecta;
    }
    public Pregunta(int idpregunta, Examen examen, String pregunta, String respuestacorrecta, Set<Respuesta> respuestas, Set<Respuesta> respuestas_1) {
       this.idpregunta = idpregunta;
       this.examen = examen;
       this.pregunta = pregunta;
       this.respuestacorrecta = respuestacorrecta;
       this.respuestas = respuestas;
       this.respuestas_1 = respuestas_1;
    }
   
    public int getIdpregunta() {
        return this.idpregunta;
    }
    
    public void setIdpregunta(int idpregunta) {
        this.idpregunta = idpregunta;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public String getRespuestacorrecta() {
        return this.respuestacorrecta;
    }
    
    public void setRespuestacorrecta(String respuestacorrecta) {
        this.respuestacorrecta = respuestacorrecta;
    }
    public Set<Respuesta> getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set<Respuesta> respuestas) {
        this.respuestas = respuestas;
    }
    public Set<Respuesta> getRespuestas_1() {
        return this.respuestas_1;
    }
    
    public void setRespuestas_1(Set<Respuesta> respuestas_1) {
        this.respuestas_1 = respuestas_1;
    }




}


