package modelo;
// Generated Nov 18, 2015 4:27:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {


     private int idrespuesta;
     private Pregunta pregunta;
     private String respuesta;
     private Set<Alumno> alumnos = new HashSet<Alumno>(0);

    public Respuesta() {
    }

	
    public Respuesta(int idrespuesta, Pregunta pregunta, String respuesta) {
        this.idrespuesta = idrespuesta;
        this.pregunta = pregunta;
        this.respuesta = respuesta;
    }
    public Respuesta(int idrespuesta, Pregunta pregunta, String respuesta, Set<Alumno> alumnos) {
       this.idrespuesta = idrespuesta;
       this.pregunta = pregunta;
       this.respuesta = respuesta;
       this.alumnos = alumnos;
    }
   
    public int getIdrespuesta() {
        return this.idrespuesta;
    }
    
    public void setIdrespuesta(int idrespuesta) {
        this.idrespuesta = idrespuesta;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public Set<Alumno> getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set<Alumno> alumnos) {
        this.alumnos = alumnos;
    }




}


